# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0a6674e00f5e43e9bfa6226e655c0b6362f263670d68425638ab336f7d42220f9da5f36c3a140fa54619cba594120ecd60dce47ba686f5c97cafaef03c62d4

test:
  secret_key_base: 3e542565c828f193f711cd1b1acdee67f5e01aba8d0214113f6b035cf1e8da94e905197c69913f3293d244e117993659af69dc6fa9a45b1c5b294a0688eec0a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV["SECRET_KEY_BASE"]
